# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: library
  pool: 5
  username: postgres
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: library
  pool: 5
  username: postgres
  password:
production:
  encoding: utf8
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
